name: test

on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "29.0.2"
          gleam-version: "1.17.0"
          rebar3-version: "3"
      - run: gleam format --check
      - run: gleam deps download
      - run: gleam test --target=erlang
      - run: gleam test --target=javascript
